name: Build Web

on:
    push:
        paths:
            - "web/**"

jobs:
    web:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 12
            - run: npx lerna bootstrap && cd web && yarn add -D typescript &&  yarn install && yarn lint
